Now honoring JAVA_HOME when taking dumps (#135)

diff --git a/dz3-shell/take-memory-dump b/dz3-shell/take-memory-dump
--- a/dz3-shell/take-memory-dump
+++ b/dz3-shell/take-memory-dump
@@ -4,8 +4,18 @@
 # It is safe to run it multiple times, each time a separate file will be created.
 
 if test -z "${JAVA_HOME}"; then
-    echo "JAVA_HOME undefined, aborting"
-    exit 1;
+    export JMAP=`which jmap`
+    if ! test -x "${JMAP}"; then
+        echo "Can't find JConsole binary";
+        exit 1;
+    fi
+else
+    export JMAP="${JAVA_HOME}/bin/jmap"
+    if ! test -x "${JMAP}"; then
+        echo "JAVA_HOME seems to point into a wrong place (${JAVA_HOME}), can't find jmap binary";
+        exit 1;
+    fi
 fi
 
-${JAVA_HOME}/bin/jmap -dump:file=`date +"%Y.%m.%d-%H:%M:%S"`.jmap `ps ax|grep net.sf.dz3.runtime.Container|grep -v grep|tr -s " "|sed -e "s:^ ::;"|cut -f 1 -d " "`
+
+${JMAP} -dump:file=`date +"%Y.%m.%d-%H:%M:%S"`.jmap `ps ax|grep net.sf.dz3.runtime.Container|grep -v grep|tr -s " "|sed -e "s:^ ::;"|cut -f 1 -d " "`
diff --git a/dz3-shell/take-thread-stack-dump b/dz3-shell/take-thread-stack-dump
--- a/dz3-shell/take-thread-stack-dump
+++ b/dz3-shell/take-thread-stack-dump
@@ -3,14 +3,25 @@
 # The following line will get the thread stack dump from the running DZ process.
 # It is safe to run it multiple times, each time a separate file will be created.
 
+# We don't need ${JAVA_HOME} *that* much, but if it is set, it'd be nice to honor it
+
 if test -z "${JAVA_HOME}"; then
-    echo "JAVA_HOME undefined, aborting"
-    exit 1;
+    export JSTACK=`which jstack`
+    if ! test -x "${JSTACK}"; then
+        echo "Can't find JConsole binary";
+        exit 1;
+    fi
+else
+    export JSTACK="${JAVA_HOME}/bin/jstack"
+    if ! test -x "${JSTACK}"; then
+        echo "JAVA_HOME seems to point into a wrong place (${JAVA_HOME}), can't find jstack binary";
+        exit 1;
+    fi
 fi
 
 OUTPUT_FILE=`date +"%Y.%m.%d-%H:%M:%S"`.stack
 
 echo "Dumping thread stack into ${OUTPUT_FILE}"
 
-${JAVA_HOME}/bin/jstack `ps ax|grep net.sf.dz3.runtime.Container|grep -v grep|tr -s " "|sed -e "s:^ ::;"|cut -f 1 -d " "` > ${OUTPUT_FILE}
+${JSTACK} `ps ax|grep net.sf.dz3.runtime.Container|grep -v grep|tr -s " "|sed -e "s:^ ::;"|cut -f 1 -d " "` > ${OUTPUT_FILE}
 
