Now aborting if JAVA_HOME is not set

diff --git a/dz3-shell/take-thread-stack-dump b/dz3-shell/take-thread-stack-dump
--- a/dz3-shell/take-thread-stack-dump
+++ b/dz3-shell/take-thread-stack-dump
@@ -3,6 +3,11 @@
 # The following line will get the thread stack dump from the running DZ process.
 # It is safe to run it multiple times, each time a separate file will be created.
 
+if test -z "${JAVA_HOME}"; then
+    echo "JAVA_HOME undefined, aborting"
+    exit 1;
+fi
+
 OUTPUT_FILE=`date +"%Y.%m.%d-%H:%M:%S"`.stack
 
 echo "Dumping thread stack into ${OUTPUT_FILE}"
